name: CMAKE Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libopencv-dev libgeographiclib-dev libfmt-dev libcgal-dev libsimdjson-dev libgdal-dev
          version: 1.0
    - name: Make Build Directory
      run: mkdir build
    - name: CMake Setup
      working-directory: ./build
      run: cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DTSR_TEST=ON
    - name: Build Tests
      working-directory: ./build
      run: ninja tsr-test
    - name: Run Tests
      working-directory: ./build
      run: ninja test
