name: CMAKE Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install deps
    - run: sudo apt install libopencv-dev libgeographiclib-dev libfmt-dev libcgal-dev libsimdjson-dev libgdal-dev
    - name: make build directory
    - run: mkdir build
    - name: cmake setup
    - run: cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DTSR_TEST=ON ..
    - name: build tests
    - run: ninja tsr-test
    - name: run tests
    - run: ninja test
